import { BaseDto } from 'ws-request-hook';
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming




export interface MemberHasLeftDto extends BaseDto {
    memberId?: string;
}

export interface ClientEntersLobbyDto extends BaseDto {
}

export interface ServerPutsClientInLobbyAndBroadcastsToEveryoneDto extends BaseDto {
    allClientIds?: string[];
}

export interface ServerConfirmsDto extends BaseDto {
    success?: boolean;
}

export interface ServerSendsErrorMessageDto extends BaseDto {
    error?: string;
}

/** Available eventType constants */
export enum StringConstants {
    MemberHasLeftDto = "MemberHasLeftDto",
    ClientEntersLobbyDto = "ClientEntersLobbyDto",
    ServerPutsClientInLobbyAndBroadcastsToEveryoneDto = "ServerPutsClientInLobbyAndBroadcastsToEveryoneDto",
    ServerConfirmsDto = "ServerConfirmsDto",
    ServerSendsErrorMessageDto = "ServerSendsErrorMessageDto",
}

